version: '3.1'
services:
    web-server:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        environment:
            domain: decision-radar.com
        ports:
            - 5001:80
            - 5002:443
        volumes:
            - ./nginx:/nginx/
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot  
        depends_on:
            - web-app
            - certbot          
        networks:
            - my-network                                
    web-app:
        build:
            context: ./app
            dockerfile: Dockerfile
        image: flask:0.0.1       
        container_name: webapp-flask
        volumes:
            - ./app:/app/
        networks:
            my-network:
                aliases:
                    - flask-app
    certbot:
        image: linuxserver/letsencrypt
        container_name: letsencrypt
        cap_add:
        - NET_ADMIN
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Amsterdam
        - URL=decision-radar.com
        - SUBDOMAINS=www,
        - VALIDATION=http
        - DNSPLUGIN=cloudflare #optional
        volumes:
        - /config:/config
        ports:
        - 443:443
        - 80:80 #optional
        restart: unless-stopped                          
networks:
    my-network:                    