version: '3.7'
services:
    web-app:
        build:
            context: ./app
            dockerfile: Dockerfile
        image: flask:0.0.1       
        container_name: webapp-flask
        volumes:
            - ./app:/app/
        networks:
            my-network:
                aliases:
                    - flask-app    
    web-server:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        environment:
            domain: decision-radar.com
        ports:
            - 5001:80
            - 5002:443
        volumes:
            - ./nginx:/nginx/ 
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot            
        depends_on:
            - web-app
            - certbot-app
        networks:
            - my-network
    certbot-app:
        build:
            context: ./letsencrypted
            dockerfile: Dockerfile       
        container_name: letsencrypted
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot  
        networks:
            my-network:
                aliases:
                    - flask-app               
networks:
    my-network:                    